services:

  wordpress-1:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: db
    volumes:
      - wordpress-1:/var/www/html
    networks:
      - cliente-1
      - rede-proxy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - cliente-1
      - rede-proxy
  db2:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db2
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db2:/var/lib/mysql
    networks:
      - cliente-1
      - rede-proxy

  wordpress-2:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db2
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: db2
    volumes:
      - wordpress-2:/var/www/html
    networks:
      - cliente-1
      - rede-proxy


  openssh-server:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    container_name: openssh-server
    hostname: openssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=true
      - USER_NAME=user
      - USER_PASSWORD=testing
      - PASSWORD_ACCESS=true
    volumes:
      - ssh:/config
    ports:
      - 2222:2222
    networks:
      - cliente-1

  

volumes:
  wordpress-1:
  wordpress-2:
  db:
  db2:
  ssh:

networks:
  cliente-1:
    driver: bridge
  rede-proxy:
    external: true