services:


  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: dns
    ports:
      - "53:53/udp"
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    networks:
      - provedor
    ports:
      - "80:80/tcp"
    depends_on:
      - asa-mail

  asa-mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
    ports: 
      - "25:25/tcp"
      - "587:587/tcp"
      - "110:110/tcp"
      - "143:143/tcp"
    container_name: asa-mail
    networks:
      - provedor
    volumes: 
      - mail:/var/mail

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adm
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - provedor


  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - SMTP_HOST=mail.matheus.asa.br
      - MAIL_FROM_ADDRESS=matheus.asa.br
      - MAIL_DOMAIN=mail.matheus.asa.br
    networks:
      - provedor

volumes:
  mail:
  nextcloud:
  db:
    




networks:
  provedor:
    driver: bridge